[package]
name = "bs58"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bs58 = "0.4.0"

[dev-dependencies]
criterion = "0.4"

[[bench]]
name = "my_benchmark"
harness = false
